Update_ci_cd.yaml

diff --git a/.github/workflows/ci_cd.yaml b/.github/workflows/ci_cd.yaml
--- a/.github/workflows/ci_cd.yaml
+++ b/.github/workflows/ci_cd.yaml
@@ -33,7 +33,12 @@ jobs:
  
       - name: Install dependencies
         run: |
+         if [ -f requirements.txt ]; then
           pip install -r requirements.txt
+         else
+          echo "requirements.txt not found!"
+          exit 1
+         fi
  
       - name: Run smoke tests
         run: pytest tests/smoke/ --junitxml=smoke-results.xml
